export const BOOKS_CATEGORY_CLASS_MAP = {
    literature: "bg-amber-300",
    HumanDevelopment: "bg-blue-300",
    HadithAndItsSciences: "bg-green-300",
    JurisprudencePrinciplesObjectives: "bg-red-300",
    TheQuranAnditsSciences: "bg-orange-300",
    theLanguage: "bg-lime-300",
    AlgeriaHistory: "bg-teal-300",
    HistoryAndBiographies: "bg-violet-300",
    DoctrineAndRecommendation: "bg-Fuchsia-300",
    IslamicThoughtAndStudies: "bg-yellow-400",
    AssociationBooks: "bg-cyan-00",
};
export const BOOKS_CATEGORY_TEXT_MAP = {
    literature: "literature",
    HumanDevelopment: "Human Development",
    HadithAndItsSciences: "Hadith and its sciences",
    JurisprudencePrinciplesObjectives: "Jurisprudence,principles objectives",
    TheQuranAnditsSciences: "The Quran and its sciences",
    theLanguage: "the language",
    AlgeriaHistory: "Algeria history",
    HistoryAndBiographies: "History and biographies",
    DoctrineAndRecommendation: "Doctrine and recommendation",
    IslamicThoughtAndStudies: "Islamic thought and studies",
    AssociationBooks: "Association books",
};
